//
//  PlayGameRouter.swift
//  RockPaperScissor
//
//  Created by Ornthita.Eae on 5/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol PlayGameRouterInput {
    func showResult(_ result: String)
}

protocol PlayGameRouterDataSource: class {
    
}

protocol PlayGameRouterDataDestination: class {
    
}

class PlayGameRouter: PlayGameRouterInput {
    
    weak var viewController: PlayGameViewController!
    weak private var dataSource: PlayGameRouterDataSource!
    weak var dataDestination: PlayGameRouterDataDestination!
    var result = ""
    
    init(viewController: PlayGameViewController, dataSource: PlayGameRouterDataSource, dataDestination: PlayGameRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        if let vc = segue.destination as? ResultViewController {
            vc.router?.dataDestination.result = self.result
        }
        
    }
    
    // MARK: Navigation
    func showResult(_ result: String) {
        self.result = result
        viewController.performSegue(withIdentifier: "segueShowResult", sender: viewController)
    }
}
