//
//  PlayGamePresenter.swift
//  RockPaperScissor
//
//  Created by Ornthita.Eae on 5/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol PlayGamePresenterInput {
    func updateScore(response: PlayGameScene.PlayGame.Response)
    func getResult(result:String,bot:String,player:String)
}

protocol PlayGamePresenterOutput: AnyObject {
    func display(response: PlayGameScene.PlayGame.Response)
    func showResult(_ result: String)
}

class PlayGamePresenter: PlayGamePresenterInput {
    weak var output: PlayGamePresenterOutput?
    
    // MARK: Presentation logic
    
}

extension PlayGamePresenter {
    func updateScore(response: PlayGameScene.PlayGame.Response) {
        output?.display(response: response)
    }
    
    func getResult(result:String,bot:String,player:String) {
        var formattedResult = bot+" vs "+player+"\n"+result
        output?.showResult(formattedResult)
    }
}
